### ISSUE TITLE
Using Word RNN for word prediction

### ISSUE THREAD

**Issue by mahmoodn1** [hunkim/word-rnn-tensorflow#11]
I am a undergraduate research assistant at Purdue University. I am attempting to use the Word RNN you have hosted on github to improve automated monkey testing (by supplying context relevant input instead of random input that the monkey uses). In a few words, I would like to give the RNN a word or phrase (the context) and would like the output of the RNN (for the monkey to use as input) to be the next predicted word. However, right now, the Word RNN implementation looks like it does only a sampling and cannot take input (a phrase or word) and output the next predicted word. Any suggestions on how to go about changing the implementation for my needs?

Example:
In a movie app, we record the following sequence:
⟨Movie,Search,Star Trek\n⟩.
And we train the RNN on similar datasets with these kind of sequences.

Later,
If I give the RNN "Movie, Search" as input, I am looking for the predicted next word, which should be relevant input for the app.

**Comment by hunkim** [comment]
Are you looking for the `--prime` option?

```python
parser.add_argument('--prime', type=str, default=' ',
                       help='prime text')
```

**Comment by mahmoodn1** [comment]
Possibly. The description of prime from the "char rnn" github repo is "Priming. It's also possible to prime the model with some starting text using -primetext. This starts out the RNN with some hardcoded characters to warm it up with some context before it starts generating text. E.g. a fun primetext might be -primetext "the meaning of life is ". I was not sure if this is the feature I was looking for. I will train the rnn on my data set and see if the prime feature is what I am looking for and reach back out to you. Thanks for the help!

**Comment by hunkim** [comment]
@mahmoodn1 Did you try our head version? I think it is fixed. Please let us know if it is not the case.
