### ISSUE TITLE
Output of sample.py

### ISSUE THREAD

**Issue by yisun92** [hunkim/word-rnn-tensorflow#12]
Hi,

I tried to train a model on the minishakespear dataset. Then, when I run sample.py, it keeps giving me output like this:

Fame,
Fame,
Fame, full complete; How many it trust no darest to lour? Dive, A merriment fled on a month. Nurse: As he, brother, at the tale his exile, thou shalt thereto with them swarm on Richmond.

There are always three "Fame" at the beginning. Even when I change the num to 1, it gives me output like:

Fame,
Fame,
Fame, Lancaster,

And in the sample function of model.py, I see this,
```
ret = prime

#other code

    pred = words[sample]
    ret += ' ' + pred
    word = pred
return ret
```

So, I think the prime string will also be included in the output, right?

Can you help me in understanding the output? Thank you.

**Comment by hunkim** [comment]
What was the option for the prime? Could you change?

**Comment by yisun92** [comment]
I think I found the problem. In model.py,

```
def sample(self, sess, words, vocab, num=200, prime='first all', sampling_type=1):
        state = self.cell.zero_state(1, tf.float32).eval()
        prime = list(vocab.keys())[2]
        print (prime)
        for word in [prime]:
            print (word)
            x = np.zeros((1, 1))
            x[0, 0] = vocab[word]
            feed = {self.input_data: x, self.initial_state:state}
            [state] = sess.run([self.final_state], feed)
```
the third line:
```
prime = list(vocab.keys())[2]
```
It assigns a word in vocab to prime. That's why it keeps giving the same output.

By the way, how to use a sentence (multiple words) as prime? It seem like this sample method can only takes a single word as prime. Otherwise, it will have a KeyError.

I'm new to rnn and tensorflow. Any help will be appreciated. Thanks a lot.

**Comment by mperiwal-kore** [comment]
I have the same question how to use sentence(multiple words) as input sequence to predict the next few words like autocomplete?

**Comment by manglakaran** [comment]
@yisun92 @mperiwal-kore Did you guys find any workaround to use a multiple words sequence as the prime text. 
If no, could @hunkim Could you suggest some workaround?

**Comment by yisun92** [comment]
@manglakaran @mperiwal-kore I found another word-rnn repo [word-rnn-tf](https://github.com/jtoy/word-rnn-tf). 

It seems works. Please let me know if it's not the case, because I'm quiet new to this technique.

**Comment by hunkim** [comment]
If that works, do you think you can send us pull request?

**Comment by manglakaran** [comment]
@hunkim I have submitted a PR, it works. Also it tends to give KeyError for words not in the current vocabulary. Looking to fix the same.

**Comment by hunkim** [comment]
Thanks. If it's not in dic can you replace it to " "?

Sung

**Comment by manglakaran** [comment]
@hunkim If it is not there in dic, replacing it with " " won't help, cause it will look for vocab[" "] which would throw a KeyError as well.

**Comment by manglakaran** [comment]
Instead of that I have given id 0 to all unseen words in the input data.

**Comment by hunkim** [comment]
Thanks! It's merged. @manglakaran @mperiwal-kore, @yisun92 Could you see if it works?

**Comment by mperiwal-kore** [comment]
[word-rnn](https://github.com/jtoy/word-rnn-tf) worked. You might get errors because of python 2 and 3. But it works. Thanks @yisun92

**Comment by mperiwal-kore** [comment]
@hunkim - can you please also look into one question I created regarding "Weighted Sampling"

**Comment by hunkim** [comment]
@manglakaran Did you try out master branch? Does it work for sampling? For your question, see #14.

**Comment by manglakaran** [comment]
@hunkim It works.

**Comment by hunkim** [comment]
@manglakaran Thanks. Now it is closed!
