### ISSUE TITLE
Weighted Sampling

### ISSUE THREAD

**Issue by mperiwal-kore** [hunkim/word-rnn-tensorflow#14]
Hey,

I am unable to understand the basis for weighted sampling to pick the next word.

`def weighted_pick(weights):
            t = np.cumsum(weights)
            s = np.sum(weights)
            return(int(np.searchsorted(t, np.random.rand(1)*s)))`
 
I also tried with `np.argmax(p)` buts its only giving same words predicted all the time.

**Comment by hunkim** [comment]
Could you execute this code?

```python
import numpy as np

def weighted_pick(weights):
    t = np.cumsum(weights)
    s = np.sum(weights)
    return (int(np.searchsorted(t, np.random.rand(1) * s)))

p = np.array([0.1, 0.5, 0.3, 0.2, 0.1])

print(np.argmax(p))
print(weighted_pick(p))
```
