### ISSUE TITLE
error while running train.py

### ISSUE THREAD

**Issue by PratikshaTaneja** [hunkim/word-rnn-tensorflow#20]
The following screenshots are errors:
Please suggest me solution
![screenshot from 2016-10-19 23_09_26](https://cloud.githubusercontent.com/assets/22937197/19548423/0c14679c-96bc-11e6-8f60-455937f6a8ce.png)

![screenshot from 2016-10-19 23_10_11](https://cloud.githubusercontent.com/assets/22937197/19548466/5d63450a-96bc-11e6-8a12-09907eb238f6.png)
![screenshot from 2016-10-19 23_10_24](https://cloud.githubusercontent.com/assets/22937197/19548472/68d43156-96bc-11e6-91de-68ff1c59b9ec.png)

**Comment by hunkim** [comment]
Resource exhausted. It seems you don't have enough memory. Could you run on a small dataset?

**Comment by PratikshaTaneja** [comment]
i have 4GB RAM. Isn't it enough for this?
