### ISSUE TITLE
WARNING:tensorflow:From train.py:85 in train.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02. Instructions for updating: Use `tf.global_variables_initializer` instead.

### ISSUE THREAD

**Issue by TheOncomingStorm** [hunkim/word-rnn-tensorflow#31]
The subject says it all. I'm still learning how to work with TF so I'm unable to correct it myself at this point..

**Comment by rishabh254** [comment]
If we follow what the warning says , replacing 'initialize_all_variables' by 'global_variables_initializer' and 'all_variables' by 'global_variables' removes the warning.

**Comment by hunkim** [comment]
@rishabh254 Could you send us a pull request?
