### ISSUE TITLE
How to tell if checkpoints are resuming? 

### ISSUE THREAD

**Issue by TheOncomingStorm** [hunkim/word-rnn-tensorflow#32]
When I use "--init_from", the count on my training starts back at 0 instead of whatever it happened to be. Is this expected?

**Comment by garker** [comment]
Eric im also using this code making many improvements

Runing in Pycharm now

Gregory Parker, Ph.D.

**Comment by hunkim** [comment]
@garker Could you send me several PRs for the improvement? Thanks!

**Comment by TheOncomingStorm** [comment]
Aaah, now that explains it. I wonder if there's a way to stop the training from resetting.

**Comment by normanheckscher** [comment]
@TheOncomingStorm I've pushed out out another PR. I saved the batch as a `tf.Variable()` which is saved in the checkpoint file and subsequently called to set the `batch_pointer` if resuming a training session. Check my code.
