### ISSUE TITLE
beam search pick - error

### ISSUE THREAD

**Issue by GenTxt** [hunkim/word-rnn-tensorflow#49]
Hi:

Training and standard sampling working perfectly in tensorflow 12.1 on 64 bit ubuntu with gpu.

Problem occurs when choosing "beam search pick" for sampling. After 15 minutes of trying to generate default 200 words the following warning appears:

/home/aaron/Desktop/word-rnn-tensorflow/beam.py:26: RuntimeWarning: divide by zero encountered in log
  cand_scores = np.array(live_scores)[:, None] - np.log(self.probs)

25 minutes still no terminal output or redirect to text file.

Any ideas how I can fix this?

Thanks

**Comment by hunkim** [comment]
That part is not fully tested. Could you try with a very small dataset?

Sung

**Comment by GenTxt** [comment]
Original corpus was 6.3 megs. Trained with tinyshakespeare 1.1 megs.

Script generated random prime word (which did not happen before) but 20 minutes later there was still no terminal output for 200 words.

Previous warning message did not appear.

**Comment by normanheckscher** [comment]
Original reference:
https://github.com/hunkim/word-rnn-tensorflow/pull/29

**Comment by victorkwan** [comment]
I've attempted a solution in #51.

**Comment by normanheckscher** [comment]
I've pulled @victorkwan solution into master with latest update. Please check and open new issue if problems persist.
