### ISSUE TITLE
Can I stop train.py and resume it later?

### ISSUE THREAD

**Issue by kartikmokashii** [hunkim/word-rnn-tensorflow#60]
Pretty much what it says in the title. I've noticed that it occasionally saves the model, so I was wondering if it's safe for me to stop it and resume it later.

**Comment by normanheckscher** [comment]
When resuming you'll need to use the '--init_from' flag to set the location of the saved files which are to be resumed.

**Comment by kartikmokashii** [comment]
So I'm trying to enter $ python train.py --init_from /Users/kartikmokashi/Desktop/word-rnn-tensorflow-master/save/model.ckpt but it says that my argument must be a path

**Comment by normanheckscher** [comment]
`python train.py --init_from=/Users/kartikmokashi/Desktop/word-rnn-tensorflow-master/save/`

**Comment by kartikmokashii** [comment]
Oh thanks I just tried that and it works
