### ISSUE TITLE
How I can continue train.py after reboot?

### ISSUE THREAD

**Issue by igarbera** [hunkim/word-rnn-tensorflow#69]
Hello! My server was rebooted and i need to continue train, but have an error:

`[root@adm word-rnn-tensorflow]# python3.6 train.py --data_dir="./data/adm_seotexts" --save_dir="./save/adm_seotexts" --init-from=./save/adm_seotexts

usage: train.py [-h] [--data_dir DATA_DIR] [--input_encoding INPUT_ENCODING]
[--log_dir LOG_DIR] [--save_dir SAVE_DIR]
[--rnn_size RNN_SIZE] [--num_layers NUM_LAYERS]
[--model MODEL] [--batch_size BATCH_SIZE]
[--seq_length SEQ_LENGTH] [--num_epochs NUM_EPOCHS]
[--save_every SAVE_EVERY] [--grad_clip GRAD_CLIP]
[--learning_rate LEARNING_RATE] [--decay_rate DECAY_RATE]
[--gpu_mem GPU_MEM] [--init_from INIT_FROM]
train.py: error: unrecognized arguments: --init-from=./save/adm_seotext`

But I have needed data in save path: 

`[root@adm word-rnn-tensorflow]# ls save/adm_seotexts/
checkpoint                            model.ckpt-82000.meta                 model.ckpt-84000.data-00000-of-00001  model.ckpt-85000.index                model.ckpt-86000.meta
config.pkl                            model.ckpt-83000.data-00000-of-00001  model.ckpt-84000.index                model.ckpt-85000.meta                 words_vocab.pkl
model.ckpt-82000.data-00000-of-00001  model.ckpt-83000.index                model.ckpt-84000.meta                 model.ckpt-86000.data-00000-of-00001
model.ckpt-82000.index                model.ckpt-83000.meta                 model.ckpt-85000.data-00000-of-00001  model.ckpt-86000.index
`
Other variants also not working (only --init-from for example):

`[root@tubeadmin word-rnn-tensorflow]# python3.6 train.py  --init-from="./save/tubeadmin_seotexts"

usage: train.py [-h] [--data_dir DATA_DIR] [--input_encoding INPUT_ENCODING]
                [--log_dir LOG_DIR] [--save_dir SAVE_DIR]
                [--rnn_size RNN_SIZE] [--num_layers NUM_LAYERS]
                [--model MODEL] [--batch_size BATCH_SIZE]
                [--seq_length SEQ_LENGTH] [--num_epochs NUM_EPOCHS]
                [--save_every SAVE_EVERY] [--grad_clip GRAD_CLIP]
                [--learning_rate LEARNING_RATE] [--decay_rate DECAY_RATE]
                [--gpu_mem GPU_MEM] [--init_from INIT_FROM]
train.py: error: unrecognized arguments: --init-from=./save/tubeadmin_seotexts`

How can I run train.py for continue training? Please help) Training ended after 2 weeks, do not want to start from the beginning :)))

**Comment by TheOncomingStorm** [comment]
I don't think there's an "=" in that usage. Maybe removing that helps?

**Comment by igarbera** [comment]
no, it not helps  - still the same error

train.py: error: unrecognized arguments: --init-from

**Comment by normanheckscher** [comment]
--init_from

It's an underscore not a hyphen.
